POST http://localhost:3333/api/cards/generate
Content-Type: application/json
# 3c34ed6c-c799-46fb-a986-660673ff668d
# 33a3d3f5-c5e5-4cee-a19c-072c64e15b0d
# 3577b388-47a3-4f13-891a-1bb43238bd74

{
    "title": "Primeiro Sorteio",
    "number_of_cards": 10,
    "unit_price": 6.50,
    "min": 1,
    "max": 100,
    "amount_random_number": 4,
    "client_id": "33a3d3f5-c5e5-4cee-a19c-072c64e15b0d",
    "date_sort": "12/12/2022"
}

###
GET http://localhost:3333/api/cards/
user-uuid: 33a3d3f5-c5e5-4cee-a19c-072c64e15b0d


###
PUT http://localhost:3333/api/cards/update/ab64d3d6-0e4f-463d-8c7f-654e8f0eb4e3
Content-Type:  application/json

{
    "new_status": "Sorteado",
    "value_sorted": 2878
}

###
DELETE http://localhost:3333/api/cards/delete/cd3dd7a5-2a94-4173-8313-0ea6f96a5f46


### 

# User Auth Methods

POST http://localhost:3333/api/users/register
Content-Type: application/json

{
    "user_name": "Leo Farias",
    "enterprise_name": "Google",
    "email": "leozin.farias@gmail.com",
    "password": "123123admin",
    "roles":["admin"]
}

###
POST http://localhost:3333/api/users/login
Content-Type: application/json

{
    "email": "victor720hugo@gmail.com",
    "password": "admin123123"
}
